source:      .
destination: ./_site
includes:    ./_includes
# baseurl: /msaveski
url: "https://samizwei.github.io"
baseurl: ""   # empty because it’s at the root
collections:
  projects:
    output: true
